Use git pull --rebase without explicit remote/branch to rely on tracking config

diff --git a/.github/workflows/workflowhub-build-dump.yml b/.github/workflows/workflowhub-build-dump.yml
--- a/.github/workflows/workflowhub-build-dump.yml
+++ b/.github/workflows/workflowhub-build-dump.yml
@@ -41,7 +41,7 @@ jobs:
           git config --local user.name "Tools Platform Ecosystem bot"
           git add .
           if git commit -m "build bioschemas RDF dump on $(date)"; then
-              git pull --rebase origin master || { git rebase --abort; echo "rebase failed, exiting"; exit 1; }
+              git pull --rebase || { git rebase --abort; echo "rebase failed, exiting"; exit 1; }
               git push origin HEAD
               echo "successfully created new data"
           else
